### ISSUE TITLE
Automate "featured" view at the dataset level

### ISSUE THREAD

**Issue by Hoedic** [deniszgonjanin/ckanext-featuredviews#1]
Currently the featured view displayed at the dataset level has to be determined manually by the user. As consequence is that most dataset might not have any view featured for the following reason:

In the context of portals,
1. most of the people who will upload data will not be that familiar with the tool
2. Several large producers automate the data flow (e.g harvesting), so nobody will go on the portal to add a view
3. For geospatial data, when done manually, the geojson file might not be available all the time (need to time generate the geojson from shp or kml) so the user won't be able to select the correct file.

Would it be possible to make it automatic: if not featured view exists for a dataset, if an existing format can be used for preview, use it. 

Note: 
- That might be difficult to manage if we want to wait until the geojson is generated)
- It might be necessary to have a check box at the package level to disable to auto-generation.

**Comment by Hoedic** [comment]
@deniszgonjanin - Additional comment: I might be needed to put configuration field to tell when automated featured views should be triggered:
- Format or type of visualisation (it's possible that users will want to specify that only map view would be featured
- Size of the file (when not in datastore): large files, for example when displayed on map might take really too much time loading. So it might be worthwhile to limite the size.

**Comment by deniszgonjanin** [comment]
Dataset-level featured views now work, but there are other points in this issue that are not addressed. I am going to break it up into several smaller issues.
